export const APP_NAME = '미래SMT ERP'
export const APP_SHORT_NAME = '미래SMT'
export const COMPANY_NAME_EN = 'MIRAE SMT CO.'
export const COMPANY_ADDRESS = '12098 Avenida Sivrita San Diego, CA 92128'
export const COMPANY_QUOTE_EMAIL = 'calvin.ha@miraesmt.com'
