/** 인쇄 시 글자 크기·배치를 맞추기 위한 공통 클래스 */
export const PRINT_SHEET = 'document-print-sheet'
export const PRINT_CONTENT = 'document-print-content'
export const PRINT_TITLE = 'document-print-title'
export const PRINT_SUBTITLE = 'document-print-subtitle'
export const PRINT_LABEL = 'document-print-label'
export const PRINT_VALUE = 'document-print-value'
export const PRINT_SECTION_TITLE = 'document-print-section-title'
export const PRINT_BODY = 'document-print-body'
export const PRINT_TABLE = 'document-print-table'
export const PRINT_TABLE_LABEL = 'document-print-table-label'
export const PRINT_TABLE_VALUE = 'document-print-table-value'
export const PRINT_DIVIDER = 'document-print-divider'
export const PRINT_CLOSING = 'document-print-closing'
